spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 500
  datasource:
   username: root
   password: 12345678
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/imooc?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
